### ISSUE TITLE
UI Updates for educator dashboard

### ISSUE THREAD

**Issue by patudom** [cosmicds/educator_dashboard#14]
Summary section
- [x] Freeze header row
- [x] Make student rows scrollable in case a teacher has more students than will fit on one screen.
- [ ] Add "out of" column for MC points (and %?)
- [x] Add % progress column

Free response and MC tables
- [x] Put "full question" text right below the "short" version of the question so teacher can see them together. (At the top feels too far away/unrelated).
- [x] Possibly build new component where the questions & free responses are set up more like in the Story where there is a question and then there is a box where the student's text is displayed.

**Comment by johnarban** [comment]
I believe this can be marked as done since there is no "out of" for MC points.
