### ISSUE TITLE
Class Summary, Free Response Tab Breadcrumbs scroll up with page content

### ISSUE THREAD

**Issue by patudom** [cosmicds/educator_dashboard#21]
The breadcrumbs menu on the right (that say "Stage 4" "Stage 5" etc should stay fixed on the screen and remain in view when the user scrolls through the free responses. Instead, they are fixed to the top of the Stage 4 content, so when the user scrolls up, the menu disappears.

**Comment by johnarban** [comment]
This was implemented in #36 in 11f3f677a2c956e00a45b6ed259e18d5c1a2fef8
