### ISSUE TITLE
Free response - organize divs as a list rather than a table

### ISSUE THREAD

**Issue by patudom** [cosmicds/educator_dashboard#28]
Student ID/Name 1

Response

rv.divider()

Student ID/Name 2

Response

rv.divider()

etc

**Comment by johnarban** [comment]
How it looks in PR #30 

instead of using rv.divider, it just uses a bottom border on the `response-row` class. 

<img width="568" alt="image" src="https://github.com/cosmicds/educator_dashboard/assets/7862929/0bf4380a-52aa-4b1f-8ca7-e62b15f59e92">
