### ISSUE TITLE
Add functionality that allows dev team to bypass educator code check

### ISSUE THREAD

**Issue by patudom** [cosmicds/educator_dashboard#64]
@johnarban will add functionality that allows the dev team to bypass this code check. Teachers' codes will be stored in the db with lists of which classes those codes have access to.

Wait to merge #43 until we have that going.

_Originally posted by @patudom in https://github.com/cosmicds/educator_dashboard/issues/43#issuecomment-1761721729_

**Comment by johnarban** [comment]
this is added in several new commits on #43 - we should work out what flow we want for it. currently it completely bypasses the code check and provides a list of classes (with no manual input box).
